#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

status=0

# Check missing dates
_scripts/add-dates.sh
if [ $? -eq 1 ]
then
  status=1
fi

_scripts/check-missing-opengraph.sh
if [ $? -eq 1 ]
then
  status=1
fi

exit $status
