#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

status=0

# Check missing dates
dates_result=$(_scripts/add-dates.sh)
if [ $? -eq 1 ]
then
  echo "$dates_result"
  status=1
fi

# opengraph_result=$(_scripts/check-missing-opengraph.sh)
# if [ $? -eq 1 ]
# then
#   echo "$opengraph_result"
#   status=1
# fi

exit $status
