# https://zellwk.com/blog/github-actions-deploy/

name: Deploy to AlwaysData

on:
  push:
    branches: ['main']
  workflow_dispatch:

env:
  MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}

concurrency:
  group: deploy
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Rsync
        uses: burnett01/rsync-deployments@7.1.0
        with:
          switches: --archive --checksum --compress --delete-after --no-inc-recursive --human-readable --stats
          path: _site/
          remote_path: ${{ secrets.RSYNC_REMOTE_PATH }}
          remote_host: ${{ secrets.RSYNC_REMOTE_HOST }}
          remote_user: ${{ secrets.RSYNC_REMOTE_USER }}
          remote_key: ${{ secrets.RSYNC_REMOTE_PRIVATE_KEY }}