name: '📸 → 🦣 POSSE photos to Mastodon'
on:
  schedule:
  # https://crontab.guru/#9_5,11,17_*_*_*
  # At minute 9 past hour 7, 13 and 19 (GMT+2).
  - cron: '9 5,11,17 * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  Mastodon:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 📥
        uses: actions/checkout@v4

      - name: POSSE photos to Mastodon
        uses: nhoizey/github-action-feed-to-mastodon@canary
        with:
          feedUrl: 'https://nicolas-hoizey.photo/feeds/mastodon/photos.json'
          mastodonInstance: ${{ secrets.MASTODON_INSTANCE }}
          mastodonToken: ${{ secrets.MASTODON_ACCESS_TOKEN }}
          cacheFile: 'posse-mastodon-photo.json'
          cacheTimestampFile: 'posse-mastodon-photo-timestamp.json'
          globalDelayToots: 300 # 5 hours (with a 6 hours difference in cron runs)
          nbTootsPerItem: 1000
          itemChoiceStrategy: "newest"
          ignoreFirstRun: false

      - name: Pull any changes from Git 📥
        run: git pull

      - name: Commit and push 📤
        uses: stefanzweifel/git-auto-commit-action@v5
